definitions:
  main.FailResult:
    properties:
      code:
        description: 状态码
        example: -1
        type: integer
      msg:
        description: 消息
        example: fail
        type: string
    type: object
  main.LoginRequest:
    properties:
      name:
        description: 用户名
        example: admin
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
    type: object
  main.SuccessResult:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 数据
      msg:
        description: 消息
        type: string
    type: object
  main.User:
    properties:
      id:
        description: ID
        example: 1
        type: integer
      name:
        description: 用户名
        example: jack
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/upload:
    post:
      consumes:
      - multipart/form-data
      description: Excel文件上传
      parameters:
      - description: Excel文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SuccessResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.FailResult'
      security:
      - ApiKeyAuth: []
      summary: Excel文件上传
      tags:
      - Excel文件上传
  /api/v1/user/addUser:
    post:
      consumes:
      - application/json
      description: 添加用户信息
      parameters:
      - description: 请求参数
        in: body
        name: 请求参数
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/main.SuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/main.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.FailResult'
      security:
      - ApiKeyAuth: []
      summary: 添加用户信息
      tags:
      - 用户
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 请求参数
        in: body
        name: 请求参数
        required: true
        schema:
          $ref: '#/definitions/main.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SuccessResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.FailResult'
      summary: 用户登录
      tags:
      - 用户
  /api/v1/user/queryById/{id}:
    get:
      consumes:
      - application/json
      description: 根据ID获取用户信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/main.SuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/main.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.FailResult'
      security:
      - ApiKeyAuth: []
      summary: 根据ID获取用户信息
      tags:
      - 用户
  /api/v1/user/queryByName:
    get:
      consumes:
      - application/json
      description: 根据用户名获取用户信息
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/main.SuccessResult'
            - properties:
                data:
                  $ref: '#/definitions/main.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.FailResult'
      security:
      - ApiKeyAuth: []
      summary: 根据用户名获取用户信息
      tags:
      - 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authentication
    type: apiKey
swagger: "2.0"
